version: "3.7"

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./backend/:/app
    tty: true
    environment:
      NODE_ENV: local

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: test
    ports:
      - 5432:5432
    volumes:
      - "./dbdata:/var/lib/postgresql/data"
